### PR TITLE
Build for Deb, Rpm

### PR DESCRIPTION
**Pull request by dragonBall561**

### CODE REVIEW

**Comment by dragonBall561** [comment]
Because I want a deb because I use debian based OS, rpm because ppl will want it for redhat based os. Also I think AppImages are a big pain to work with, and it's more convenient to have deb/rpm packages

**Comment by dragonBall561** [comment]
> Secondly, with your changes it is still not possible to build deb and rpm files. Because this target needs the author email to be sepcified in the package.json which currently isn't the case.

Yes sorry about that I'll fix it...

**Comment by jely2002** [comment]
Hi, is this still relevant?
Closing this PR in a couple days if not.

**Comment by jely2002** [comment]
Closing the PR as this doesn't seem relevant anymore.

**Pull request closed without merging**
