### PR TITLE
Add `auto` file format option for audio-only downloads

### PR DESCRIPTION
**Pull request by NebelNidas**
Keep the source audio codec to maintain the original quality. This is youtube-dl's default behavior.

Closes https://github.com/jely2002/youtube-dl-gui/issues/137.

### CODE REVIEW

**Review by jely2002 — COMMENTED** [review]
Looks good to me. If you remove the draft status, I will test it locally and approve.

**Comment by NebelNidas** [comment]
The reason I haven't removed the draft status yet is because I'm still struggling with thumbnail embedding. I can't set `--embed-thumbnail` globally, as that will leave behind the image files if merging failed. But I still want to have thumbnail embedding for the containers which support it (mp3 and m4a). Unfortunately, as far as I can see, there's now way to know beforehand what container the final file will end up in?

So currently, my idea is to download the video first, then let youtube-dl extract the audio, and when that's done, check the container and, if compatible, download the thumbnail and merge it into the audio container with ffmpeg. Do you know of a better way to accomplish this? It would of course be simpler if unmergeable thumbnails wouldn't be left behind, but I haven't received an answer yet if this is accomplishable: https://github.com/ytdl-org/youtube-dl/issues/29568

**Comment by jely2002** [comment]
I have made a function that removes the leftover image file if embedding fails.
```js
    async removeThumbnail() {
        const filename = this.video.filename;
        if(filename != null) {
            const filenameExt = path.basename(filename, path.extname(filename)) + ".jpg";
            const filenameAbs = path.join(this.video.downloadedPath, filenameExt);
            try {
                await fs.promises.unlink(filenameAbs);
            } catch(e) {
                console.error("Unable to remove failed image embed.");
                console.error(filenameExt);
                console.error(filenameAbs);
            }
        }
    }
```

This means you can add the `none` format to the check at line 34 DownloadQuery.js.
```js
if(audioOutputFormat === "m4a" || audioOutputFormat === "mp3" || audioOutputFormat === "none") {
    args.push("--embed-thumbnail");
}
```

And call the `removeThumbnail()` function just before returning the result at the end of the connect function in DownloadQuery.js. Like so:
```js
if(this.environment.settings.audioOutputFormat === "none") {
    await this.removeThumbnail();
}
```

**Comment by NebelNidas** [comment]
Thank you very much, it works great! 😊 Now I just have to catch the merging error correctly, should be done in ~5 min. At which line would you like me to put the `removeThumbnail()` function?

**Comment by jely2002** [comment]
I put that function all the way at the bottom of DownloadQuery.js!

**Comment by NebelNidas** [comment]
Should be working now!

**Review by jely2002 — APPROVED** [review]
Looks good and works when I test. Good catch by adding an exception to the ErrorHandler.
There is one failing test, will fix that myself after merge.

**Pull request merged**
