### PR TITLE
Same FileName Saving

### LINKED ISSUE #455: File Not Being Saved When Playlist Contains Video Of The Same Name.
**Describe the bug**
Youtube Videos of the same name in a playlist don't get downloaded or fail to save to disk after the first one is saved to disk.  
Even when the names don't match by their case.

**To Reproduce**
1. Add two different videos of the same name to a youtube playlist
2. Add Playlist link to [youtube-dl-gui](https://github.com/jely2002/youtube-dl-gui)
3. Download Video or Audio
4. App will say it has downloaded 2 videos but on the folder, there will be only one of them.

**Expected behavior**
When it fails to save the file, it should append the duplicate count of the name,
For eg. 
Playlist Video Content -  "ENCASSATOR - Psychotronics inc" , "ENCASSATOR - PSYCHOTRONICS INC" and "encassator - Psychotronics inc" 

First one getting download will be named as "ENCASSATOR - Psychotronics inc.mp4"
the 2nd one should be saved as "ENCASSATOR - PSYCHOTRONICS INC(1).mp4"
the 3rd one should be saved as "encassator - Psychotronics inc(2).mp4"

### PR DESCRIPTION
**Pull request by Zenodeon**
Fixes #455

PR Fixes files not being saved when a file with the same name exists in the download folder.

It is fixed by creating a new temp folder (named by the unique identifier) in the download folder for each video. 

Then all the embedding and processing are done in this folder and once done, the final file (be it mp4, opus, or whatever the user has requested) will be moved out of the temp folder. 

While moving it out, it checks for any pre-existing file with the same name, and if it exists, it adds "(n)" to the file name where n represents the duplicate file name count.

After Moving the processed file, the temp folder is forced Deleted.

### CODE REVIEW

**Comment by Zenodeon** [comment]
@StefanLobbenmeier

**Comment by StefanLobbenmeier** [comment]
Hey :) I don’t own this repo, you will have to create the pr in my fork

**Comment by StefanLobbenmeier** [comment]
https://github.com/StefanLobbenmeier/youtube-dl-gui/pulls

**Comment by Zenodeon** [comment]
oh i did not know they stopped maintaining this project, will pr in your fork

**Comment by Zenodeon** [comment]
Done

**Pull request closed without merging**
