### PR TITLE
Update electron-builder npm module

### PR DESCRIPTION
**Pull request by trick77**
This allows for the UI to be built specifically for Apple Silicon.

### CODE REVIEW

**Comment by jely2002** [comment]
Does this mean I will have to build 2 versions of the mac executable? One for arm64 and one for x64?

**Comment by trick77** [comment]
This should pack both architectures into a single dmg:
```npx electron-builder --universal```

However, I've noticed the macOS ffmpeg static binary in /binaries is Intel only. Whatever your source is for these binaries, maybe there's an universal macOS binary available too which you could use instead.

**Comment by trick77** [comment]
Sure, it works. I'm using the Homebrew Apple Silicon ffmpeg Version by replacing the existing binary with a Symlink. This works fine as well but requires some tinkering. It would be awesome to have some sort of existing ffmpeg binary autodetection.

**Comment by jely2002** [comment]
Fun fact, there already is ffmpeg binary auto-detection if the program can sucessfully run ffmpeg and ffprobe in terminal it should not install ffmpeg.

The code for this is here:
https://github.com/jely2002/youtube-dl-gui/blob/a8f27029891dfb4efd06edf3436b87acb00671cb/modules/FfmpegUpdater.js#L58

**Pull request closed without merging**
